# Generated by Django 4.2.2 on 2023-06-06 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=200, verbose_name='Surname')),
                ('name', models.CharField(max_length=150, verbose_name='Name')),
                ('patronymic', models.CharField(max_length=200, verbose_name='Patronymic')),
                ('author_describe', models.TextField(blank=True, verbose_name='Author describe')),
                ('birthday', models.DateTimeField(verbose_name='Birthday')),
            ],
            options={
                'verbose_name': 'Жанр',
                'verbose_name_plural': 'Жанры',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(max_length=200, verbose_name='Country name')),
            ],
            options={
                'verbose_name': 'Страна',
                'verbose_name_plural': 'Страны',
            },
        ),
        migrations.CreateModel(
            name='Genres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre_name', models.CharField(max_length=100, verbose_name='Genre name')),
            ],
            options={
                'verbose_name': 'Жанр',
                'verbose_name_plural': 'Жанры',
            },
        ),
        migrations.CreateModel(
            name='Publishers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publishers_name', models.CharField(max_length=100, verbose_name='Publishers name')),
                ('date_registration', models.DateTimeField(auto_now_add=True, verbose_name='Date registration')),
                ('number', models.IntegerField(verbose_name='Number')),
                ('site', models.CharField(max_length=250, verbose_name='Site')),
            ],
            options={
                'verbose_name': 'Издатель',
                'verbose_name_plural': 'Издатели',
            },
        ),
        migrations.CreateModel(
            name='Games',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_name', models.CharField(max_length=100, verbose_name='Game name')),
                ('photo', models.ImageField(upload_to='gameimg/%Y/%m/%d', verbose_name='Photo')),
                ('game_describe', models.TextField(blank=True, verbose_name='Game describe')),
                ('date_publication', models.DateTimeField(auto_now_add=True, verbose_name='Date publication')),
                ('environment', models.CharField(max_length=100, verbose_name='Environment')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.author', verbose_name='Author')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.country', verbose_name='Country')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.genres', verbose_name='Genre')),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.publishers', verbose_name='Publisher')),
            ],
            options={
                'verbose_name': 'Игра',
                'verbose_name_plural': 'Игры',
            },
        ),
    ]
