# Generated by Django 4.2.2 on 2023-06-06 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'verbose_name': 'Автор', 'verbose_name_plural': 'Авторы'},
        ),
        migrations.AlterField(
            model_name='author',
            name='author_describe',
            field=models.TextField(blank=True, verbose_name='Описание автора'),
        ),
        migrations.AlterField(
            model_name='author',
            name='birthday',
            field=models.IntegerField(verbose_name='Год рождения'),
        ),
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='author',
            name='patronymic',
            field=models.CharField(blank=True, max_length=200, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='author',
            name='surname',
            field=models.CharField(max_length=200, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='country',
            name='country_name',
            field=models.CharField(max_length=200, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='games',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.author', verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='games',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.country', verbose_name='Страна производитель'),
        ),
        migrations.AlterField(
            model_name='games',
            name='date_publication',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации на сайте'),
        ),
        migrations.AlterField(
            model_name='games',
            name='environment',
            field=models.CharField(max_length=100, verbose_name='Сеттинг'),
        ),
        migrations.AlterField(
            model_name='games',
            name='game_describe',
            field=models.TextField(blank=True, verbose_name='Описание игры'),
        ),
        migrations.AlterField(
            model_name='games',
            name='game_name',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='games',
            name='genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.genres', verbose_name='Жанр'),
        ),
        migrations.AlterField(
            model_name='games',
            name='photo',
            field=models.ImageField(upload_to='gameimg/%Y/%m/%d', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='games',
            name='publisher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.publishers', verbose_name='Издатель'),
        ),
        migrations.AlterField(
            model_name='genres',
            name='genre_name',
            field=models.CharField(max_length=100, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='publishers',
            name='date_registration',
            field=models.DateField(auto_now_add=True, verbose_name='Дата регистрации'),
        ),
        migrations.AlterField(
            model_name='publishers',
            name='number',
            field=models.IntegerField(blank=True, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='publishers',
            name='publishers_name',
            field=models.CharField(max_length=100, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='publishers',
            name='site',
            field=models.URLField(max_length=250, verbose_name='Официальный сайт'),
        ),
    ]
